# Generated by Django 5.2 on 2025-05-01 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(regex='^[a-zA-Z0-9]+$')]),
        ),
    ]
